//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneMarkDotNet.Properties
{
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneMarkDotNet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        internal static string RibbonTabLabel
        {
            get
            {
                return ResourceManager.GetString("RibbonTabLabel", resourceCulture);
            }
        }

        internal static string RenderButtonLabel
        {
            get
            {
                return ResourceManager.GetString("RenderButtonLabel", resourceCulture);
            }
        }

        internal static string ExportButtonLabel
        {
            get
            {
                return ResourceManager.GetString("ExportButtonLabel", resourceCulture);
            }
        }

        internal static string SourceModeButtonLabel
        {
            get
            {
                return ResourceManager.GetString("SourceModeButtonLabel", resourceCulture);
            }
        }

        internal static string ImportButtonLabel
        {
            get
            {
                return ResourceManager.GetString("ImportButtonLabel", resourceCulture);
            }
        }

        internal static string ExportFileButtonLabel
        {
            get
            {
                return ResourceManager.GetString("ExportFileButtonLabel", resourceCulture);
            }
        }

        internal static string AboutButtonLabel
        {
            get
            {
                return ResourceManager.GetString("AboutButtonLabel", resourceCulture);
            }
        }

        internal static string ThemeMenuLabel
        {
            get
            {
                return ResourceManager.GetString("ThemeMenuLabel", resourceCulture);
            }
        }

        internal static string SelectThemeLabel
        {
            get
            {
                return ResourceManager.GetString("SelectThemeLabel", resourceCulture);
            }
        }

        internal static string OpenThemeDirLabel
        {
            get
            {
                return ResourceManager.GetString("OpenThemeDirLabel", resourceCulture);
            }
        }

        internal static string ReloadThemesLabel
        {
            get
            {
                return ResourceManager.GetString("ReloadThemesLabel", resourceCulture);
            }
        }

        internal static string StartupFailureMessage
        {
            get
            {
                return ResourceManager.GetString("StartupFailureMessage", resourceCulture);
            }
        }
    }
}
